# Generated by Django 5.0 on 2023-12-29 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_remove_like_movie'),
        ('movies', '0013_remove_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
