# Generated by Django 5.0 on 2023-12-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_movie'),
        ('likes', '0002_remove_like_movie'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.comment'),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(blank=True, to='likes.like'),
        ),
    ]
