# Generated by Django 5.0 on 2023-12-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_comments_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='to_silder',
            field=models.BooleanField(default=False),
        ),
    ]
