# Generated by Django 5.0 on 2023-12-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_person_rename_to_silder_movie_to_slider_comment_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailers/'),
        ),
    ]
