# Generated by Django 5.0 on 2023-12-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='role',
            field=models.CharField(choices=[('starring', 'Starring'), ('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer')], default='starring', max_length=255),
        ),
    ]
