# Generated by Django 5.0 on 2023-12-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_contribution_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('starring', 'Starring'), ('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer')], default='actor', max_length=255),
        ),
    ]
