# Generated by Django 5.0 on 2023-12-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_movie'),
        ('movies', '0008_person_bio_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='movie_comments', to='comments.comment'),
        ),
    ]
