# Generated by Django 5.0 on 2023-12-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_comments_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='comments',
        ),
    ]
