# Generated by Django 5.0 on 2023-12-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movie_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='likes',
        ),
    ]
