# Generated by Django 5.0 on 2023-12-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_price_userprofile_watchlist_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='movies.movie'),
        ),
    ]
