# Generated by Django 5.0 on 2023-12-31 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_userprofile_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('historical', 'Historical'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('western', 'Western')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre'),
        ),
    ]
