# Generated by Django 5.0 on 2023-12-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_movie_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('HD', 'HD'), ('SD', 'SD')], default='HD', max_length=255),
        ),
    ]
